version: '3.8'

services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile  # Certifique-se de que o nome do Dockerfile seja correto (maiusculo 'D')
    environment:
      DB_HOST: 3.141.8.42  # Substitua pelo IP real
      DB_USER: root
      DB_PASS: senha123
      DB_NAME: meubanco
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "4500:4500"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Certifique-se de que nginx.conf está no mesmo diretório que o docker-compose.yml
    depends_on:
      - php-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
